### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by leavengood**
Most are probably kosher except maybe the last one.

### CODE REVIEW

**Comment by crewjam** [comment]
Yeah, all but the last commit is cool with me. I think MessageID serves this purpose, doesn't it?

**Comment by leavengood** [comment]
Yeah that might make sense but for now we had been putting the part of the daemon, like `outboundhttps` for the MessageID.

**Comment by leavengood** [comment]
I've pulled the last commit into another branch for now, so we can just get this merged.

**Comment by crewjam** [comment]
lgtm

**Pull request merged**
